### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by NobodyOffcal** [FenrirBots/pixelproxy#1]
do you know c# i have pixel worlds bot on my resp but its broken idk how to fix also we can work together i know C++ i could help you about pixel worlds

my discord : nobodycoder

**Comment by FenrirBots** [comment]
For context, The developer later claimed his ZIP file was a rat and that he has my credit card, I don't own a credit card.
![image (1)](https://github.com/FenrirBots/pixelproxy/assets/111782432/e8075f23-f5b3-4b0a-8dca-5b28a580bbb7)

**Comment by FenrirBots** [comment]
I also never opened the ZIP file, Bro is yapping.

**Comment by FenrirBots** [comment]
After adding him on discord he claimed that I had "Downloaded his rat." and that "He has my credit card", I do not own a credit card.

![image (2)](https://github.com/FenrirBots/pixelproxy/assets/111782432/aabb2338-ebd5-4601-afb5-4cc1ef5e0643)
